name: cloud-slice-v1

on:
  workflow_dispatch:
    inputs:
      auth-token:
        description: '上传用户的token'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Cache apt-get dependencies
      uses: actions/cache@v4.1.1
      id: cache-apt
      with:
        path: /var/lib/apt/lists/
        key: ${{ runner.os }}-apt-${{ hashFiles('apt-packages.txt') }}  # 生成唯一缓存键
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install GUI Dependency & Locales
      run: |
        if [ "${{ steps.cache-apt.outputs.cache-hit }}" = "true" ]; then
          echo "Apt dependencies cached, skipping installation"
        else
          echo "Installing GUI Dependencies & locales..."
          sudo apt-get update
          sudo apt-get install -y \
            locales \
            libgl1-mesa-glx \
            libglu1-mesa \
            libx11-6 \
            libxext6 \
            libxrender1 \
            libxi6 \
            libxtst6 \
            libxt6 \
            libxfixes3 \
            libxrandr2 \
            libasound2 \
            libpango1.0-0 \
            libatk1.0-0 \
            libgtk-3-0 \
            libgstreamer1.0-0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            libfuse-dev \
            libegl1 \
            libwebkit2gtk-4.0-37 \
            xvfb \
            at-spi2-core \
            dbus-x11 \
            imagemagick
        fi

    - name: Configure locales
      run: |
        sudo locale-gen en_GB.UTF-8
        sudo dpkg-reconfigure locales

    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Setup Xauthority
      run: |
        touch $HOME/.Xauthority
        xauth nlist $DISPLAY | xauth -f $HOME/.Xauthority nmerge -

    - name: Start AT-SPI Registry
      run: |
        echo "Starting AT-SPI Registry"
        export XDG_SESSION_COOKIE=`xauth list|grep .$DISPLAY|cut -d' ' -f1`
        dbus-launch --exit-with-session
        echo "AT-SPI Registry started"

    - name: Download AppImage
      run: |
        wget https://github.com/Snapmaker/OrcaSlicer/releases/download/nightlybuild/Snapmaker_Orca_Engine_Linux_V0.0.1.AppImage -O appimage.AppImage
        chmod 777 appimage.AppImage
        
    - name: Download 3mf
      run: |
        wget https://snapmaker-public-resource.s3.amazonaws.com/device/1/air_spinner.3mf -O air_spinner.3mf
        pwd
        ls -a
      env:
        DISPLAY: ":99"
